site_name: Ansible101
repo_url: https://github.com/rafmarsan/Ansible101
site_url: https://rafmarsan.github.io/Ansible101
theme:
  features:
    - navigation.expand
    - content.code.copy
  name: material
  # logo: images/logo.png
  # favicon: images/favicon_old.png
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: es
          default: true
          name: Español
        - locale: en
          name: English
          nav_translations:
            Contenido: Content
            Introduccion: Introduction
            Fundamentos: Basics
            Variables: Variables
            Tasks, Roles y Handlers: Tasks, Roles and Handlers
            Templates: Templates
            Configurar WebServers: Configure WebServers
            Configurar Databases: Configure Databases
            Proyecto final: Final project

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Contenido:
      - Introduccion: introduction.md
      - Fundamentos: basics.md
      - Variables: vars.md
      - Tasks, Roles y Handlers: task_roles_handlers.md
      - Templates: templates.md
      - Configurar WebServers: config_webservers.md
      - Configurar Databases: config_databases.md
      - Proyecto final: final_project.md
      # - Admonitions: admonitions_list.md
