[project]
# Información general del proyecto
name = "lab"  # Nombre del proyecto. Usado para empaquetado e instalación.
version = "0.8.7"  # Versión actual del proyecto.
description = "CLI para la gestión de ejercicios de laboratorio de un curso Ansible."  # Descripción corta.
authors = [
  { name = "Rafael Marín", email = "trainedbronze@gmail.com" }
]
# Versión mínima de Python requerida.
requires-python = ">=3.10"

# Dependencias del proyecto (equivalente a install_requires en setuptools)
dependencies = [
  "typer==0.17.4",
  "typing_extensions==4.15.0",
  "rich==14.1.0",
  "podman==5.6.0",
  "paramiko==4.0.0",
  "PyYAML==6.0.3",
]
# "docker==7.1.0",

license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

[project.scripts]
# Define los scripts de consola que se instalan con el paquete.
# 'lab' será el comando que el usuario ejecuta en la terminal.
# 'lab.main:app' indica el módulo (lab/main.py) y la función Typer (app) que se llama.
lab = "lab.main:app"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# 1. Escanea de forma recursiva TODAS las subcarpetas del proyecto automáticamente
packages = { find = {} }

# 2. Configuración de datos estáticos (rutas relativas al paquete 'lab')
[tool.setuptools.package-data]
lab = [
  'infrastructure/containerfiles/*',
]

[project.urls]
Homepage = "https://github.com/rafmarsan/Ansible101"
Issues = "https://github.com/rafmarsan/Ansible101/issues"